config/routes.rb
Rails.application.routes.draw do

  root 'users#index'
  resources :dashboard, only: [:index]
  resources :users
  resources :categories
end

app/models/address.rb
class Address < ActiveRecord::Base
  belongs_to :user
  belongs_to :city
  belongs_to :state
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :products
end

app/models/city.rb
class City < ActiveRecord::Base
  has_many :addresses
end

app/models/credit_card.rb
class CreditCard < ActiveRecord::Base
  belongs_to :user
end

app/models/order.rb
class Order < ActiveRecord::Base
  has_many :order_contents
  belongs_to :user
end

app/models/order_content.rb
class OrderContent < ActiveRecord::Base
  belongs_to :order 
  belongs_to :product
end

app/models/product.rb
class Product < ActiveRecord::Base
  has_many :order_contents
  belongs_to :category
end

app/models/state.rb
class State < ActiveRecord::Base
  has_many :addresses
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :addresses
  has_many :credit_cards
  has_many :orders
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def index
    @categories=Category.all
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
    #past 7, 30, and 365 days user
    @past_time=[7,30,"all time"]
    @users_7=User.where(:created_at => (Time.now-7.day)..Time.now)
    @users_30=User.where(:created_at => (Time.now-30.day)..Time.now)
    @users_10000=User.where(:created_at => (Time.now-10000.day)..Time.now)
    @timespan_users=[@users_7,@users_30,@users_10000]

    #past orders 7,30,365
    @orders_7=Order.where(:checkout_date => (Time.now-7.day)..Time.now)
    @orders_30=Order.where(:checkout_date => (Time.now-30.day)..Time.now)
    @orders_10000=Order.where(:checkout_date => (Time.now-10000.day)..Time.now)
    @timespan_orders=[@orders_7,@orders_30,@orders_10000]

  
    @products_7=Product.where(:created_at => (Time.now-7.day)..Time.now)
    @products_30=Product.where(:created_at => (Time.now-30.day)..Time.now)
    @products_10000=Product.where(:created_at => (Time.now-10000.day)..Time.now)
    @timespan_products=[0,0,100]


    @top_three_states= User.find_by_sql ["SELECT states.name, COUNT(states.name) FROM users JOIN addresses ON (users.id=user_id) JOIN states ON (state_id = states.id) GROUP BY states.name ORDER BY COUNT(states.name) desc LIMIT 3"]
    @top_three_cities= User.find_by_sql ["SELECT cities.name, COUNT(cities.name) FROM users JOIN addresses ON (users.id=user_id) JOIN cities ON (city_id=cities.id) GROUP BY cities.name ORDER BY COUNT(cities.name) desc LIMIT 3"]

  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @user=User.find_by_sql ["SELECT DISTINCT users.id,first_name,last_name,cities.name,checkout_date FROM users JOIN addresses ON (users.id=user_id) JOIN cities ON (city_id=cities.id) JOIN orders ON (users.id=orders.user_id)"]
  end

  def create
    @user = User.new(
      first_name: params[:user][:first_name],
      last_name: params[:user][:last_name],
      email: params[:user][:email])
    if @user.save
      flash.notice= "success"
      redirect_to user_path(@user.id)
    else
      flash.now[:error] = "error"
      render :new
    end
  end

  def new
    @user=User.new
  end
  
  def show
    @user=User.find(params[:id])
  end

  def edit
    @user=User.find(params[:id])
  end

  def update
    @user=User.find(params[:id])
    @user.update ({:first_name => params[:user][:first_name]})
    @user.update ({:last_name => params[:user][:last_name]})
    @user.update ({:email => params[:user][:email]})
    redirect_to user_path(@user)
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to users_path
  end

  private
  def user_params
    params.require(:user).permit(:first_name,:last_name,:email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/users_helper.rb
module UsersHelper

end

app/views/categories/index.html.erb
<div class="container center">
	<div class="col-md-12 centered">
  <h1> Store Admin user </h1>
  	</div>
</div>

<div class="body-container">
	<div class="col-md-2 col-md-offset-1 well ">
		<p>Navigation Options</p>
		Users<br>
		Adresses<br>
		Orders<br>
		Products<br>
		<td><%=link_to"Categories",categories_path%></td><br>
		<br>
		<%=link_to "Dashboard",dashboard_index_path %>
	</div>

	<div class="col-md-8 well">
		<div class="col-md-6 col-md-offset-4">
		<h2>Store Users</h2>
		</div>

		<div class="col-md-7 col-md-offset-2">
		<%= button_to('Create New Category', new_user_path, :class => 'btn btn-primary btn-lg btn-block centered')  %>
		<li> <%=link_to "Create New Category", new_user_path %> </li>
		</div>
 		
		<div class="col-md-9 col-md-offset-1 well">
		<table>
		  <tr>
		    <th>ID</th>
		    <th>Name</th>
		    <th>City</th>
		    <th>Show</th>
		    <th>Edit</th>
		    <th>Delete</th>
		  </tr>
		  
		  <% @categories.each do |category|%>
		  <tr>
		    <td><%=category.id%></td>
		    <td><%=category.name%></td>
		    <td><%=category.description%></td>
		    <td><%=link_to"Show",category_path(category)%></td>
		    <td><%=link_to"Edit",edit_category_path(category)%></td>
		    <td><%=link_to "Delete", category_path(category), method: :delete %></td>
		  </tr>

		  <%end%>
		  
		</table>


		</div>



	</div>
</div>

app/views/dashboard/index.html.erb
<div class="container">
  <div class="col-md-12">
  	<h1> Viking Store Dashboard </h1>
  </div>
  <div class="row">
  	<div class="col-md-6 panel">
  		<h3> Overall </h3>
  		<%counter=0%>
  		<% @past_time.each do |days|%>
  		<br>
  		<p>Past <%=days%> Days</p>

		  <table class="table table-striped table-bordered">
		    <thead>
		      <tr>
		        <th>Item</th>
		        <th>Data</th>
		 
		      </tr>
		    </thead>
		    <tbody>
		      <tr>
		        <td>New users</td>
		        <td><%=@timespan_users[counter].count%></td>
		      </tr>
		      <tr>
		        <td>New Orders</td>
		        <td><%=@timespan_orders[counter].count%></td>
		      </tr>
		      <tr>
		        <td>New Products</td>
		        <td><%=@timespan_products[counter]%></td>
		      </tr>
		    </tbody>
		  </table>
		  	<%counter+=1%>

		  		<% end %>

  	</div>
  	<div class="col-md-6 panel">
  		<h3> Demographics and Behavior </h3>
  		<br>
  		<p>Top 3 States Users Live in</p>
  		<table class="table table-striped table-bordered">
		    <thead>
		      <tr>
		        <th>Item</th>
		        <th>Data</th>
		 
		      </tr>
		    </thead>
		    <tbody>
		      <tr>
		        <td><%=@top_three_states[0].name%></td>
		        <td><%=@top_three_states[0].count%></td>
		      </tr>
		      <tr>
		        <td><%=@top_three_states[1].name%></td>
		        <td><%=@top_three_states[1].count%></td>
		      </tr>
		      <tr>
		        <td><%=@top_three_states[2].name%></td>
		        <td><%=@top_three_states[2].count%></td>
		      </tr>
		    </tbody>
		  </table>

		  <br>
		  <p>Top 3 Cities Users Live in</p>
  		<table class="table table-striped table-bordered">
		    <thead>
		      <tr>
		        <th>Item</th>
		        <th>Data</th>
		 
		      </tr>
		    </thead>
		    <tbody>
		      <tr>
		        <td><%=@top_three_cities[0].name%></td>
		        <td><%=@top_three_cities[0].count%></td>
		      </tr>
		      <tr>
		        <td><%=@top_three_cities[1].name%></td>
		        <td><%=@top_three_cities[1].count%></td>
		      </tr>
		      <tr>
		        <td><%=@top_three_cities[2].name%></td>
		        <td><%=@top_three_cities[2].count%></td>
		      </tr>
		    </tbody>
		  </table>

		   <br>
		  <p>Top User With...</p>
		  <table class="table table-striped table-bordered">
		    <thead>
		      <tr>
		        <th>Item</th>
		        <th>User</th>
		        <th>Quantity</th>

		 
		      </tr>
		    </thead>
		    <tbody>
		      <tr>
		        <td>Highest Single Order Value</td>
		        <td>Mark Zachary</td>
		        <td>$995</td>
		      </tr>
		      <tr>
		        <td></td>
		        <td></td>
		      </tr>
		    </tbody>
		  </table>


  	</div>




 <!--  </div>
   <div class="row">
  	<div class="col-md-6 panel">
  		<h3> Order Statistics </h3>
  	</div>
  	<div class="col-md-6 panel">
  		<h3> Time Statistics </h3>
  	</div>
  </div> -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SolutionVikingStore</title>

  <!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>


<p class="flash"><%= flash.notice %></p>

<%= yield %>

</body>
</html>

app/views/users/edit.html.erb
Fill in the correct information:

<%= form_for @user do |f| %>
  <%= f.label :first_name %>
  <%= f.text_field :first_name %>
  <%= f.label :last_name %>
  <%= f.text_field :last_name %>
  <%= f.label :email %>
  <%= f.text_field :email %>
  <%= f.submit "Create" %>
<% end %>

app/views/users/index.html.erb
<div class="container center">
	<div class="col-md-12 centered">
  <h1> Store Admin user </h1>
  	</div>
</div>

<div class="body-container">
	<div class="col-md-2 col-md-offset-1 well ">
		<p>Navigation Options</p>
		Users<br>
		Adresses<br>
		Orders<br>
		Products<br>
		<td><%=link_to"Categories",categories_path%></td><br>
		<br>
		<%=link_to "Dashboard",dashboard_index_path %>
	</div>

	<div class="col-md-8 well">
		<div class="col-md-6 col-md-offset-4">
		<h2>Store Users</h2>
		</div>

		<div class="col-md-7 col-md-offset-2">
		<%= button_to('Create New User', new_user_path, :class => 'btn btn-primary btn-lg btn-block centered')  %>
		<li> <%=link_to "Create New User", new_user_path %> </li>
		</div>
 		
		<div class="col-md-9 col-md-offset-1 well">
		<table>
		  <tr>
		    <th>ID</th>
		    <th>Name</th>
		    <th>City</th>
		    <th>Order Date</th>
		    <th>Show</th>
		    <th>Edit</th>
		    <th>Delete</th>
		  </tr>
		  
		  <% @user.each do |user|%>
		  <tr>
		    <td><%=user.id%></td>
		    <td><%=user.first_name%> <%=user.last_name%></td>
		    <td><%=user.name%></td>
		    <td><%=user.checkout_date%></td>
		    <td><%=link_to"Show",user_path(user)%></td>
		    <td><%=link_to"Edit",edit_user_path(user)%></td>
		    <td><%=link_to "Delete", user_path(user), method: :delete %></td>
		  </tr>

		  <%end%>
		  
		</table>


		</div>



	</div>
</div>

app/views/users/new.html.erb
<h1>Fill out the following to create a new user</h1>

 <% @user.errors.full_messages.each do |msg| %>
  <li><%= msg %></li>
  <% end %>

<%= form_for @user do |f| %>
  <%= f.label :first_name %>
  <%= f.text_field :first_name %>
  <%= f.label :last_name %>
  <%= f.text_field :last_name %>
  <%= f.label :email %>
  <%= f.text_field :email %>
  <%= f.submit "Create" %>
<% end %>

app/views/users/show.html.erb
<div class="container center">
	<h2> User<%=@user.id%> : <%=@user.first_name%> <%=@user.last_name%></h2>
	<div class="col-md-10">
		<div class="demographic-container row">
			<h5>Demographic Information</h5>
			<p>First Name: <%=@user.first_name%><br>
				Last Name: <%=@user.last_name%><br>
				Email: <%=@user.email%><br>
				Default Billing Address : <%=@user.addresses.first.street_address%>, <%=@user.addresses.first.city.name%>, <%=@user.addresses.first.state.name%><br>
				Default Shipping Address : <%=@user.addresses.last.street_address%>, <%=@user.addresses.first.city.name%>, <%=@user.addresses.first.state.name%>
			</p>
			<td><%=link_to"Edit User",edit_user_path(@user)%></td><br>
			<td><%=link_to "Delete User", user_path(@user), method: :delete %></td>
		</div>
		     <br>
		<div class="credit-container row">
			<h5>Credit Card Info</h5>
			<p><p>First Name: <%=@user.first_name%><br>
				Last Name: <%=@user.last_name%><br>
				Card Number: <%=@user.credit_cards.first.card_number%><br>
				Expiration Date: <%=@user.credit_cards.first.exp_year%>-<%=@user.credit_cards.first.exp_month%>


		</div>
	</div>
</div>